---
- name: Install prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes

- name: Symlink dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .zpreztorc
    - .zlogin
    - .zlogout
    - .gitignore
    - .zshrc
    - .config
    - .gitconfig
    - .tmux

- name: Install tmux-plugin-manager
  git:
    - repo: https://github.com/tmux-plugins/tpm
    - dest: ~/.tmux/plugins/tpm

- name: Install dein
  raw: mkdir ~/.dein && curl -fsSL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | bash -s ~/.dein
