---
- name: Install prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes

- name: Symlink dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .zpreztorc
    - .zlogin
    - .zlogout
    - .gitignore
    - .zshrc
    - .config
    - .gitconfig
    - .tmux.conf
    - .chunkwmrc
    - .skhdrc

- name: Install tmux-plugin-manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: Create dein folder
  file: path=~/.dein state=directory

- name: Fetch dein install script
  get_url: url=https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh dest=/tmp/dein_install.sh

- name: Install dein
  script: /tmp/dein_install.sh ~/.dein
