---
- name: Install prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes

- name: Symlink dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .zpreztorc
    - .zlogin
    - .zlogout
    - .gitignore
    - .zshrc
    - .config
    - .gitconfig

- name: Install dein
  raw: mkdir ~/.dein && sh -c "$(curl -fsSL https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh)" ~/.dein
