---
- name: Install homebrew
  shell: 'yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  args:
    creates: /usr/local/bin/brew

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - tig
    - gettext
    - graphviz
    - fortune
    - git
    - pv
    - n
    - tldr
    - neovim
    - ranger
    - zsh
    - zsh-syntax-highlighting
    - watch
    - python
    - python3
    - wget
    - node
    - httpie
    - cask
    - tree
    - openssl
    - ack
    - nmap
    - curl
    - htop

- name: Install apps with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - vlc
    - aerial
    - google-chrome
    - skype
    - alfred
    - docker
    - virtualbox
    - vagrant
    - vagrant-manager
    - dropbox
    - flux
    - spectacle
    - radiant-player
    - postman
    - macdown

- name: Cleanup Brew packages
  command: brew cleanup
