---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Tap brew formulae
  homebrew_tap: name={{ item }} state=present
  with_items:
    - crisidev/homebrew-chunkwm

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - tig
    - gettext
    - graphviz
    - fortune
    - git
    - pv
    - n
    - tldr
    - neovim
    - ranger
    - zsh
    - zsh-syntax-highlighting
    - watch
    - python
    - python3
    - wget
    - node
    - httpie
    - cask
    - tree
    - openssl
    - ack
    - nmap
    - curl
    - htop
    - fasd
    - tmux

- name: Install apps with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - vlc
    - aerial
    - google-chrome
    - skype
    - alfred
    - docker
    - virtualbox
    - vagrant
    - vagrant-manager
    - dropbox
    - ngrok
    - flux
    - spectacle
    - radiant-player
    - postman
    - macdown
    - coconutbattery
    - dash
    - karabiner-elements
    - viscosity

- name: Cleanup Brew packages
  command: brew cleanup
