---
- name: Install pip pkgs
  pip: name={{ item }}
  with_items:
    - virtualenv
    - howdoi

- name: Install pip3 pkgs
  pip: name={{ item }} executable=pip3
    with_items:
      - asciinema
      - neovim
